kind: Job
apiVersion: batch/v1
metadata:
  name: nemo-evaluate
spec:
  template:
    spec:
      containers:
      - name: nemo-evaluate
        image: thomasjo/nemo:tensorflow-2.2.0
        workingDir: /storage/nemo
        command:
        - bin/pyrun
        - python/evaluate_model.py
        # - /data/partitions/2019-06/test
        - /data/generated
        - output/128x128
        - output/nemo--128x128--best.h5
        - --image-size=128
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
