kind: Job
apiVersion: batch/v1
metadata:
  name: nemo-finetune
spec:
  template:
    spec:
      containers:
      - name: nemo-finetune
        image: thomasjo/nemo:tensorflow-2.2.0
        workingDir: /storage/nemo
        command:
        - bin/pyrun
        - python/finetune_model.py
        - /data/partitions/2020-05
        - output/new-data
        - output/nemo--best.h5
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
