kind: Job
apiVersion: batch/v1
metadata:
  name: nemo-suite
spec:
  template:
    spec:
      containers:
      - name: nemo-suite
        image: thomasjo/nemo:tensorflow-2.2.0
        workingDir: /storage/nemo
        command:
        - bin/pyrun
        - python/training_suite.py
        # <source>
        - /data/partitions/2020-05
        # <output>
        - output/new-data/suite
        # <model>
        # - output/nemo-ft--best.h5
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
