kind: Job
apiVersion: batch/v1
metadata:
  name: nemo-train
spec:
  template:
    spec:
      containers:
      - name: nemo-train
        image: thomasjo/nemo:latest
        workingDir: /storage/nemo
        command:
        - python3
        - python/train_model.py
        - data
        - output
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
